services:
  mysql:
    image: 'mysql:9.1'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=1234'
      - 'MYSQL_ROOT_PASSWORD=1234'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
